############### English navigation ################

# [[main]]
# weight = 1
# name = "SC23 AWS Schedule"
# url = "/sc23/"
# hasChildren = false

# [[main]]
# weight = 1
# name = "AWS @ ISC'24"
# url = "/isc24/"
# hasChildren = false

[[main]]
weight = 1
name = "Tech Notes"
url = "/blog/"
hasChildren = false

# [[main]]
# weight = 2
# name = "Learn"
# url = "/learning/"
# hasChildren = true

[[main]]
weight = 3
name = "Products"
url = "/products/"
hasChildren = true

# [[main]]
# weight = 4
# name = "Workloads"
# hasChildren = true
# 
# [[main]]
# parent = "Workloads"
# name = "AI/ML"
# url = "/ai-ml/"
# weight = 1
# 
# [[main]]
# parent = "Workloads"
# name = "CAE/CFD"
# url = "/cae-cfd/"
# weight = 2
# 
# [[main]]
# parent = "Workloads"
# name = "Climate, Environment & Weather"
# url = "/climate-environment-weather/"
# weight = 3
# 
# [[main]]
# parent = "Workloads"
# name = "Life Sciences"
# url = "/life-sciences/"
# weight = 4

[[main]]
weight = 5
name = "About"
url = "about/"
hasChildren = false

# [[main]]
# weight = 6
# name = "Resources"
# url = "/resources/"
# hasChildren = false

# footer "Quick Links" menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Contact"
url = "contact/"
weight = 2
